version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/www/
      - /www/.next
      - /www/node_modules
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

